### PR TITLE
useFormat24 for resolving relative time ago

### LINKED ISSUE #148: 24h support for relative time not working
The feature for switching the time format from 12 am/p to 24h is not used for relative time.

### PR DESCRIPTION
**Pull request by a-nickol**
Uses useFormat24 config for relative time. 
Fixes #148.
Tests & documentation are still unchanged.

### CODE REVIEW

File: lib/assets/javascripts/src/local-time/relative_time.coffee [hunk 1]
```diff
@@ -70,4 +70,7 @@ class LocalTime.RelativeTime
     strftime(@date, format)
 
   toTimeString: ->
-    strftime(@date, getI18nValue("time.formats.default"))
+    strftime(@date, if @useFormat24
+      getI18nValue("time.formats.default_24h")
+    else
+      getI18nValue("time.formats.default"))
```
Comment (josefarias) [inline lib/assets/javascripts/src/local-time/relative_time.coffee:76]: I think we can do away with all diffs in the controller if we just import the config in this file and do something like:

```suggestion
    format = if config.useFormat24 then "default_24h" else "default"
    strftime @date, getI18nValue("time.formats.#{format}")
```

If that works, let's do that instead.

**Review by josefarias — CHANGES_REQUESTED** [review]
Thanks for the PR! I left a comment explaining how I think this could be simplified.

We should get some tests for this as well before merging.

**Comment by josefarias** [comment]
While we're at it, probably good to account for 24h format here, too:
https://github.com/basecamp/local_time/blob/28a2d685b88a3985beebfb4d8bdb5cf965866163/lib/assets/javascripts/src/local-time/controller.coffee#L39-L41

File: lib/assets/javascripts/src/local-time/relative_time.coffee (hunk 1 above)
Comment (a-nickol) [reply lib/assets/javascripts/src/local-time/relative_time.coffee:76]: Do you think it should fallback to default if default_24h is missing? This would be easier for other which upgrade the lib.

Comment (josefarias) [reply lib/assets/javascripts/src/local-time/relative_time.coffee:76]: Let's include a test for this nonetheless, to protect us from breaking it in the future

**Comment by a-nickol** [comment]
I have currently problems to fix the existing tests. 

My timezone is "Mitteleuropäische Normalzeit" which is not parsed correctly by `parseTimeZone` in `strftime.coffee`.

The first regex should maybe be something like `string.match(/\(([\p{Letter}\s]+)\)$/u)?[1]` but i don't know about the second one.

**Comment by a-nickol** [comment]
I think i did the needed changes.

File: README.md [hunk 2]
```diff
@@ -174,6 +174,10 @@ Time::DATE_FORMATS[:simple] = "%-l:%M%P"
 Time::DATE_FORMATS[:simple_24h] = "%H:%M"
 ```
 
+To format the relative time e.g. when `:type` is set to `time-ago`, `config.useFormat24` is used, too. Depending on the configuration the following keys are used to get for the corresponding formats from the `I18n` configuration: `time.formats.default` or `time.formats.default_24h`.
+
+For the title of the html element either `datetime.formats.default` or `datetime.formats.default_24h` is used depending on the configuration set.
```
Comment (josefarias) [inline README.md:179]:
```suggestion
When `:type` is set to `time-ago`, the format is obtained from the `I18n` [configuration](#configuration).
```

I think this is enough of an explanation for now. I plan to revisit the readme as a whole for the next release.

File: lib/assets/javascripts/src/local-time/controller.coffee [hunk 3]
```diff
@@ -37,7 +37,8 @@ class LocalTime.Controller
     return if isNaN time
 
     unless element.hasAttribute("title")
-      title = strftime(time, getI18nValue("datetime.formats.default"))
+      datetime_format = if config.useFormat24 then "default_24h" else "default"
+      title = strftime(time, getI18nValue("datetime.formats.#{datetime_format}"))
```
Comment (josefarias) [inline lib/assets/javascripts/src/local-time/controller.coffee:41]:
```suggestion
      title_format = if config.useFormat24 then "default_24h" else "default"
      title = strftime(time, getI18nValue("datetime.formats.#{title_format}"))
```

File: test/javascripts/src/test_helpers.coffee [hunk 4]
```diff
@@ -34,6 +34,9 @@ LocalTime.TestHelpers =
     # reading the text content, not a potentially arbitrary property.
     el.innerHTML
 
+  getTitle: (el) ->
+    el.getAttribute('title')
```
Comment (josefarias) [inline test/javascripts/src/test_helpers.coffee:38]:
```suggestion
    el.getAttribute("title")
```

File: test/javascripts/src/format24_test.coffee [hunk 5]
```diff
@@ -44,3 +44,58 @@ testGroup "format24 (24h time)", ->
...
+    expected = "#{day} at #{time}"
+
+    originalFormat24 = config.useFormat24
+    config.useFormat24 = false
+
+    el = addTimeEl type: "time-ago", datetime: ago.toISOString()
+    defer ->
+      assert.equal getText(el), expected
+      config.useFormat24 = originalFormat24
+      done()
```
Comment (josefarias) [inline test/javascripts/src/format24_test.coffee:61]:
```suggestion
  testAsync "turned off for relative time elements", (done) ->
    ago = moment().subtract("days", 5)
    originalFormat24 = config.useFormat24
    config.useFormat24 = false

    el = addTimeEl type: "time-ago", datetime: ago.toISOString()
    defer ->
      assert.equal getText(el), "#{ago.format("dddd")} at #{ago.format("h:mma")}"
      config.useFormat24 = originalFormat24
      done()
```

This is probably just personal preference. I think the variables here don't communicate any information about the test, they're just acting as data holders with a label. That's fine, but this data isn't complex enough to need a label or anything. So let's just drop them.

Let's make the same edits on the `turned on relative time` test

File: test/javascripts/src/format24_test.coffee [hunk 6]
```diff
@@ -44,3 +44,58 @@ testGroup "format24 (24h time)", ->
...
+    ago = moment().subtract("days", 5)
+
+    originalFormat24 = config.useFormat24
+    config.useFormat24 = false
+
+    el = addTimeEl type: "time-ago", datetime: ago.toISOString()
+    defer ->
+      assert.equal getTitle(el), ago.format('MMMM D, YYYY [at] h:mma ');
+      config.useFormat24 = originalFormat24
+      done()
```
Comment (josefarias) [inline test/javascripts/src/format24_test.coffee:88]:
```suggestion
  testAsync "element title when turned off", (done) ->
    ago = moment().subtract("days", 5)
    originalFormat24 = config.useFormat24
    config.useFormat24 = false

    el = addTimeEl type: "time-ago", datetime: ago.toISOString()
    defer ->
      assert.equal getTitle(el), ago.format("MMMM D, YYYY [at] h:mma");
      config.useFormat24 = originalFormat24
      done()
```

The other tests don't have that empty line between the subject variable assignment and the config. It's not wrong or bad, just making the change for consistency. Same goes for using double quotes instead of single ones.

Why is the space at the end of the expected text necessary? Does the result of `ago.format('MMMM D, YYYY [at] h:mma ')` include that space? If so, ideally we'd avoid that, assuming it's not an existing bug in the library.

Let's make the same edits to the `turned on title` test.

**Review by josefarias — CHANGES_REQUESTED** [review]
Great work @a-nickol this is really close!

I left a couple more comments for your consideration. Thanks for the hard work on this!

Also, could you resolve the merge conflicts, please? Should be a matter of:

1. Deleting the conflicting files in your branch (don't worry, they're easy to regenerate)
2. Merging `main` back into your branch, or rebasing your branch on top of `main`
3. Re-running the tests with `rake test`

Note that the tests should be passing now in your machine with the latest changes on `main`.

File: lib/assets/javascripts/src/local-time/relative_time.coffee (hunk 1 above)
Comment (josefarias) [reply lib/assets/javascripts/src/local-time/relative_time.coffee]: > Let's include a test for this nonetheless, to protect us from breaking it in the future

Ah, we already test for this:

https://github.com/basecamp/local_time/blob/1395c561faae447e41da8319b05e6e4bbac294c9/test/javascripts/src/i18n_test.coffee#L35-L49

**Comment by a-nickol** [comment]
> Note that the tests should be passing now in your machine with the latest changes on `main`.

I don't know why, but tests about timezone are failing again, i have commented it in #150.

**Review by josefarias — APPROVED** [review]
Great work on this. Thank you @a-nickol!
